# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '__first__'),
        ('player', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='developer.Developer')),
                ('players', models.ManyToManyField(related_name='games', to='player.Player')),
            ],
        ),
    ]
