# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('A', 'Action'), ('RP', 'Role Playing'), ('FPS', 'FPS'), ('SM', 'Simulation'), ('SR', 'Stratergy'), ('O', 'Other'), ('S', 'Select Game Category')], default='S', max_length=8)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('highest_score', models.DecimalField(decimal_places=2, default=0, max_digits=16, null=True)),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='developer.Developer')),
            ],
        ),
    ]
