# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0003_game_last_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_purchased',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
