# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0004_auto_20170225_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
