# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0008_auto_20170225_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('A', 'Action'), ('RP', 'Role Playing'), ('FPS', 'FPS'), ('SM', 'Simulation'), ('SR', 'Stratergy'), ('O', 'Other')], default='S', max_length=8),
        ),
    ]
