# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cart_games',
            field=models.ManyToManyField(blank=True, related_name='cart_games', to='gamedata.Game'),
        ),
    ]
