# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_playergamedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamedata',
            name='game_save_data',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
