# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_playergamedata_game_save_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activation_key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='player',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
